[package]
name = "crudlove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.5"
syn = { version = "2.0.18", features = ["full", "extra-traits"] }
